export const errorCode = {
  missingRequiredFields: "MISSING_REQUIRED_FIELDS",
  invalidRequiredDate: "INVALID_REQUIRED_DATE",
  invalidTier: "INVALID_TIER",
  invalidProduct: "INVALID_PRODUCT",
  tooManyProducts: "TOO_MANY_PRODUCTS",
  productNotEligible: "PRODUCT_NOT_ELIGIBLE_FOR_TIER",
  productMixExceedsTier: "PRODUCT_MIX_EXCEEDS_TIER",
  invalidOccasion: "INVALID_OCCASION",
  policyVersionMismatch: "POLICY_VERSION_MISMATCH",
  invalidIdempotencyKey: "INVALID_IDEMPOTENCY_KEY",
  paymentReferenceUsed: "PAYMENT_REFERENCE_ALREADY_USED",
  rateLimited: "RATE_LIMITED",
  unauthorized: "UNAUTHORIZED",
  invalidCredentials: "INVALID_CREDENTIALS",
  invalidStatus: "INVALID_STATUS",
  invalidStatusTransition: "INVALID_STATUS_TRANSITION",
  shippingRequired: "SHIPPING_DETAILS_REQUIRED",
  invalidShipping: "INVALID_SHIPPING_DETAILS",
  invalidUpload: "INVALID_UPLOAD_REQUEST",
  invalidVideoKey: "INVALID_VIDEO_KEY",
  invalidVideoObject: "INVALID_VIDEO_OBJECT",
  invalidTrackingToken: "INVALID_TRACKING_TOKEN",
  packingVideoNotReady: "PACKING_VIDEO_NOT_READY",
  invalidIssueReport: "INVALID_ISSUE_REPORT",
  issueNotAllowed: "ISSUE_NOT_ALLOWED_FOR_STATUS",
  issueWindowExpired: "ISSUE_WINDOW_EXPIRED",
  orderNotFound: "ORDER_NOT_FOUND",
  invalidContentType: "INVALID_CONTENT_TYPE",
  invalidJson: "INVALID_JSON",
  requestTooLarge: "REQUEST_TOO_LARGE",
  originRequired: "ORIGIN_REQUIRED",
  invalidOrigin: "INVALID_ORIGIN",
  crossSiteBlocked: "CROSS_SITE_REQUEST_BLOCKED",
  orderServiceUnavailable: "ORDER_SERVICE_UNAVAILABLE",
  trackingServiceUnavailable: "TRACKING_SERVICE_UNAVAILABLE",
  adminLoginUnavailable: "ADMIN_LOGIN_UNAVAILABLE",
  logoutFailed: "LOGOUT_FAILED",
  statusUpdateFailed: "STATUS_UPDATE_FAILED",
  shippingUpdateFailed: "SHIPPING_UPDATE_FAILED",
  uploadServiceUnavailable: "UPLOAD_SERVICE_UNAVAILABLE",
  packingVideoUpdateFailed: "PACKING_VIDEO_UPDATE_FAILED",
  approvalServiceUnavailable: "APPROVAL_SERVICE_UNAVAILABLE",
  issueServiceUnavailable: "ISSUE_SERVICE_UNAVAILABLE",
  unknown: "UNKNOWN"
} as const

export type ErrorCode = (typeof errorCode)[keyof typeof errorCode]
