import { chmodSync, writeFileSync } from "node:fs";

const isProduction = process.env.NODE_ENV === "production";
const canonicalMangalamErpUrl = "https://app.mangalamsanitary.in";
const isGuardedDeployment = Boolean(process.env.DEPLOY_SHA);
const approvedProductionHosts = new Set([
  "app.mangalamsanitary.in",
  "client.trustfirstsolutions.in",
  "mangalamsanitary.in",
  "www.mangalamsanitary.in",
]);

if (
  isProduction &&
  isGuardedDeployment &&
  process.env.PRODUCTION_URL === canonicalMangalamErpUrl
) {
  process.env.AUTH_TRUST_HOST ||= "true";
  process.env.AUTH_URL ||= canonicalMangalamErpUrl;
  process.env.NEXTAUTH_URL ||= canonicalMangalamErpUrl;
}

const required = [
  { key: "DATABASE_URL", validate: isUrl },
  { key: "AUTH_SECRET", validate: (value) => value.length >= 32 },
  ...(isProduction
    ? [
        { key: "AUTH_TRUST_HOST", validate: (value) => value === "true" },
        { key: "AUTH_URL", validate: isApprovedProductionUrl },
        { key: "NEXTAUTH_URL", validate: isApprovedProductionUrl },
      ]
    : []),
  ...(isProduction && isGuardedDeployment
    ? [
        {
          key: "PRODUCTION_URL",
          validate: (value) => value === canonicalMangalamErpUrl,
        },
      ]
    : []),
];

const recommended = isProduction
  ? []
  : [
      { key: "AUTH_URL", validate: isUrl },
      { key: "NEXTAUTH_URL", validate: isUrl },
    ];

const failures = [];
const warnings = [];

for (const entry of required) {
  const value = process.env[entry.key];
  if (!value) {
    failures.push(`${entry.key} is missing.`);
    continue;
  }
  if (!entry.validate(value)) {
    failures.push(`${entry.key} is present but invalid.`);
  }
}

for (const entry of recommended) {
  const value = process.env[entry.key];
  if (!value) {
    warnings.push(`${entry.key} is not set.`);
    continue;
  }
  if (!entry.validate(value)) {
    warnings.push(`${entry.key} is present but invalid.`);
  }
}

if (
  isProduction &&
  isGuardedDeployment &&
  (process.env.TRUSTFIRST_ALLOW_LOOPBACK_STAGING === "true" ||
    process.env.TRUSTFIRST_DEMO_MODE === "staging")
) {
  failures.push("Production deployment contains forbidden staging loopback settings.");
}

if ((process.env.AUTH_SECRET?.length ?? 0) < 64) {
  warnings.push("AUTH_SECRET should be at least 64 characters for production rotation strength.");
}

if (warnings.length > 0) {
  console.warn("Environment warnings:");
  for (const warning of warnings) console.warn(`- ${warning}`);
}

if (failures.length > 0) {
  console.error("Environment validation failed:");
  for (const failure of failures) console.error(`- ${failure}`);
  process.exit(1);
}

if (isProduction && isGuardedDeployment) {
  /* Next.js loads runtime env files from the application root, not monorepo root. */
  const runtimeEnvPath = "apps/web/.env.production.local";
  const runtimeEnv = [
    "# Generated by scripts/validate-env.mjs during guarded production deployment.",
    "AUTH_TRUST_HOST=true",
    `AUTH_URL=${canonicalMangalamErpUrl}`,
    `NEXTAUTH_URL=${canonicalMangalamErpUrl}`,
    "",
  ].join("\n");

  writeFileSync(runtimeEnvPath, runtimeEnv, {
    encoding: "utf8",
    mode: 0o600,
  });
  chmodSync(runtimeEnvPath, 0o600);
  console.log(`Canonical production auth settings materialized at ${runtimeEnvPath}.`);
}

console.log("Environment validation passed.");

function isApprovedProductionUrl(value) {
  try {
    const url = new URL(value);
    return url.protocol === "https:" && approvedProductionHosts.has(url.hostname);
  } catch {
    return false;
  }
}

function isUrl(value) {
  try {
    new URL(value);
    return true;
  } catch {
    return false;
  }
}
